/** @format */
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const initRooms: string[] = ["FirstRoom", "SecondRoom"];

export interface Bid {
	name: string;
	bid: number;
}

const Home: NextPage = () => {
	const [myName, setMyName] = useState<string>();
	const router = useRouter();

	useEffect(() => {
		if (!sessionStorage.getItem("user")) {
			router.push("/login");
		}
	}, []);
	return (
		<div className=''>
			<Head>
				<title>Online Auction</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className=''>
				<section className='text-xl'>
					<h1>WELCOME {myName}</h1>
					<input
						type='text'
						onChange={(e) => {
							setMyName(e.target.value);
						}}
						placeholder='Name'></input>
				</section>
				<h1 className='text-xl font-bold text-red-600 mt-10'>Join a room </h1>
				<section>
					{initRooms.map((room, i) => (
						<div key={i}>
							<h1>{room}</h1>
							<button
								value={room}
								className='animate-pulse text-green-600 transition-transform duration-1000'
								onClick={(e) => {
									e.preventDefault();
									if (myName === "") {
										return;
									} else {
										router.push({
											pathname: "/biddingroom",
											query: { room: e.currentTarget.value, name: myName },
										});
									}
								}}>
								Join
							</button>
						</div>
					))}
				</section>
			</main>
		</div>
	);
};

export default Home;
